import {
  FaSun,
  FaMoon,
  FaSearch,
  FaVolumeMute,
  FaBackward,
  FaForward,
  FaChevronLeft,
} from "react-icons/fa";
import { ImVolumeLow } from "react-icons/im";
import { IoVolumeHighOutline } from "react-icons/io5";
import { IoPlaySkipForwardOutline } from "react-icons/io5";
import { FaPowerOff } from "react-icons/fa6";
import { CiGrid32 } from "react-icons/ci";
import { CiMicrophoneOn } from "react-icons/ci";
import { FaWindows } from "react-icons/fa6";
import { FaRegMoon } from "react-icons/fa";

import { KeyProps } from "../component/SingleKey";

export const topRowKeys: KeyProps[] = [
  {
    width: "lg",
    keytop: null,
    keybottom: "esc",
    topAlign: "left",
    bottomAlign: "left",
    justify: "end",
  },
  {
    width: "normal",
    keytop: FaSun,
    keybottom: "F1",
    topAlign: "center",
    bottomAlign: "center",
  },
  {
    width: "normal",
    keytop: FaMoon,
    keybottom: "F2",
    topAlign: "center",
    bottomAlign: "center",
  },
  {
    width: "normal",
    keytop: CiGrid32,
    keybottom: "F3",
    topAlign: "center",
    bottomAlign: "center",
  },
  {
    width: "normal",
    keytop: FaSearch,
    keybottom: "F4",
    topAlign: "center",
    bottomAlign: "center",
  },
  {
    width: "normal",
    keytop: CiMicrophoneOn,
    keybottom: "F5",
    topAlign: "center",
    bottomAlign: "center",
  },
  {
    width: "normal",
    keytop: FaRegMoon,
    keybottom: "F6",
    topAlign: "center",
    bottomAlign: "center",
  },
  {
    width: "normal",
    keytop: FaBackward,
    keybottom: "F7",
    topAlign: "center",
    bottomAlign: "center",
  },
  {
    width: "normal",
    keytop: IoPlaySkipForwardOutline,
    keybottom: "F8",
    topAlign: "center",
    bottomAlign: "center",
  },
  {
    width: "normal",
    keytop: FaForward,
    keybottom: "F9",
    topAlign: "center",
    bottomAlign: "center",
  },
  {
    width: "normal",
    keytop: FaVolumeMute,
    keybottom: "F10",
    topAlign: "center",
    bottomAlign: "center",
  },
  {
    width: "normal",
    keytop: ImVolumeLow,
    keybottom: "F11",
    topAlign: "center",
    bottomAlign: "center",
  },
  {
    width: "normal",
    keytop: IoVolumeHighOutline,
    keybottom: "F12",
    topAlign: "center",
    bottomAlign: "center",
  },
  {
    width: "normal",
    keytop: FaPowerOff,
    keybottom: null,
    topAlign: "center",
    bottomAlign: "center",
  },
];

export const SecondRowKeys: KeyProps[] = [
  {
    width: "normal",
    keybottom: "~",
    keytop: "`",
    topAlign: "center",
    bottomAlign: "center",
    justify: "center",
  },
  {
    width: "normal",
    keybottom: "1",
    keytop: "!",
    topAlign: "center",
    bottomAlign: "center",
    justify: "center",
  },
  {
    width: "normal",
    keybottom: "2",
    keytop: "@",
    topAlign: "center",
    bottomAlign: "center",
    justify: "center",
  },
  {
    width: "normal",
    keybottom: "3",
    keytop: "#",
    topAlign: "center",
    bottomAlign: "center",
    justify: "center",
  },
  {
    width: "normal",
    keybottom: "4",
    keytop: "$",
    topAlign: "center",
    bottomAlign: "center",
    justify: "center",
  },
  {
    width: "normal",
    keybottom: "5",
    keytop: "%",
    topAlign: "center",
    bottomAlign: "center",
    justify: "center",
  },
  {
    width: "normal",
    keybottom: "6",
    keytop: "^",
    topAlign: "center",
    bottomAlign: "center",
    justify: "center",
  },
  {
    width: "normal",
    keybottom: "7",
    keytop: "&",
    topAlign: "center",
    bottomAlign: "center",
    justify: "center",
  },
  {
    width: "normal",
    keybottom: "8",
    keytop: "*",
    topAlign: "center",
    bottomAlign: "center",
    justify: "center",
  },
  {
    width: "normal",
    keybottom: "9",
    keytop: "(",
    topAlign: "center",
    bottomAlign: "center",
    justify: "center",
  },
  {
    width: "normal",
    keybottom: "0",
    keytop: ")",
    topAlign: "center",
    bottomAlign: "center",
    justify: "center",
  },
  {
    width: "normal",
    keybottom: "-",
    keytop: "_",
    topAlign: "center",
    bottomAlign: "center",
    justify: "center",
  },
  {
    width: "normal",
    keybottom: "=",
    keytop: "+",
    topAlign: "center",
    bottomAlign: "center",
    justify: "center",
  },
  {
    width: "lg",
    keybottom: "delete",
    keytop: "",
    topAlign: "center",
    bottomAlign: "right",
    justify: "end",
  },
];

export const ThirdRowKeys: KeyProps[] = [
  {
    width: "lg",
    keybottom: "tab",
    keytop: "",
    topAlign: "center",
    bottomAlign: "left",
    justify: "start",
  },
  {
    width: "normal",
    keytop: "Q",
    topAlign: "center",
    bottomAlign: "center",
    justify: "center",
  },
  {
    width: "normal",
    keytop: "W",
    topAlign: "center",
    bottomAlign: "center",
    justify: "center",
  },
  {
    width: "normal",
    keytop: "E",
    topAlign: "center",
    bottomAlign: "center",
    justify: "center",
  },
  {
    width: "normal",
    keytop: "R",
    topAlign: "center",
    bottomAlign: "center",
    justify: "center",
  },
  {
    width: "normal",
    keytop: "T",
    topAlign: "center",
    bottomAlign: "center",
    justify: "center",
  },
  {
    width: "normal",
    keytop: "Y",
    topAlign: "center",
    bottomAlign: "center",
    justify: "center",
  },
  {
    width: "normal",
    keytop: "U",
    topAlign: "center",
    bottomAlign: "center",
    justify: "center",
  },
  {
    width: "normal",
    keytop: "I",
    topAlign: "center",
    bottomAlign: "center",
    justify: "center",
  },
  {
    width: "normal",
    keytop: "O",
    topAlign: "center",
    bottomAlign: "center",
    justify: "center",
  },
  {
    width: "normal",
    keytop: "P",
    topAlign: "center",
    bottomAlign: "center",
    justify: "center",
  },
  {
    width: "normal",
    keybottom: "[",
    keytop: "{",
    topAlign: "center",
    bottomAlign: "center",
    justify: "center",
  },
  {
    width: "normal",
    keybottom: "]",
    keytop: "}",
    topAlign: "center",
    bottomAlign: "center",
    justify: "center",
  },
  {
    width: "normal",
    keybottom: "\\",
    keytop: "|",
    topAlign: "center",
    bottomAlign: "center",
    justify: "center",
  },
];

export const FourthRowKeys: KeyProps[] = [
  {
    width: "xl",
    keybottom: "caps",
    keytop: "",
    topAlign: "center",
    bottomAlign: "left",
    justify: "start",
  },
  {
    width: "normal",
    keytop: "A",
    topAlign: "center",
    bottomAlign: "center",
    justify: "center",
  },
  {
    width: "normal",
    keytop: "S",
    topAlign: "center",
    bottomAlign: "center",
    justify: "center",
  },
  {
    width: "normal",
    keytop: "D",
    topAlign: "center",
    bottomAlign: "center",
    justify: "center",
  },
  {
    width: "normal",
    keytop: "F",
    topAlign: "center",
    bottomAlign: "center",
    justify: "center",
  },
  {
    width: "normal",
    keytop: "G",
    topAlign: "center",
    bottomAlign: "center",
    justify: "center",
  },
  {
    width: "normal",
    keytop: "H",
    topAlign: "center",
    bottomAlign: "center",
    justify: "center",
  },
  {
    width: "normal",
    keytop: "J",
    topAlign: "center",
    bottomAlign: "center",
    justify: "center",
  },
  {
    width: "normal",
    keytop: "K",
    topAlign: "center",
    bottomAlign: "center",
    justify: "center",
  },
  {
    width: "normal",
    keytop: "L",
    topAlign: "center",
    bottomAlign: "center",
    justify: "center",
  },
  {
    width: "normal",
    keybottom: ";",
    keytop: ":",
    topAlign: "center",
    bottomAlign: "center",
    justify: "center",
  },
  {
    width: "normal",
    keybottom: "'",
    keytop: '"',
    topAlign: "center",
    bottomAlign: "center",
    justify: "center",
  },
  {
    width: "xl",
    keybottom: "enter",
    keytop: "",
    topAlign: "center",
    bottomAlign: "right",
    justify: "end",
  },
];

export const FifthRowKeys: KeyProps[] = [
  {
    width: "2xl",
    keybottom: "shift",
    keytop: "",
    topAlign: "center",
    bottomAlign: "left",
    justify: "start",
  },
  {
    width: "normal",
    keytop: "Z",
    topAlign: "center",
    bottomAlign: "center",
    justify: "center",
  },
  {
    width: "normal",
    keytop: "X",
    topAlign: "center",
    bottomAlign: "center",
    justify: "center",
  },
  {
    width: "normal",
    keytop: "C",
    topAlign: "center",
    bottomAlign: "center",
    justify: "center",
  },
  {
    width: "normal",
    keytop: "V",
    topAlign: "center",
    bottomAlign: "center",
    justify: "center",
  },
  {
    width: "normal",
    keytop: "B",
    topAlign: "center",
    bottomAlign: "center",
    justify: "center",
  },
  {
    width: "normal",
    keytop: "N",
    topAlign: "center",
    bottomAlign: "center",
    justify: "center",
  },
  {
    width: "normal",
    keytop: "M",
    topAlign: "center",
    bottomAlign: "center",
    justify: "center",
  },
  {
    width: "normal",
    keybottom: ",",
    keytop: "<",
    topAlign: "center",
    bottomAlign: "center",
    justify: "center",
  },
  {
    width: "normal",
    keybottom: ".",
    keytop: ">",
    topAlign: "center",
    bottomAlign: "center",
    justify: "center",
  },
  {
    width: "normal",
    keybottom: "/",
    keytop: "?",
    topAlign: "center",
    bottomAlign: "center",
    justify: "center",
  },
  {
    width: "2xl",
    keybottom: "shift",
    keytop: "",
    topAlign: "center",
    bottomAlign: "right",
    justify: "end",
  },
];

export const SixthRowKeys: KeyProps[] = [
  {
    width: "normal",
    keybottom: "ctrl",
    keytop: "",
    topAlign: "center",
    bottomAlign: "center",
    justify: "center",
  },
  {
    width: "normal",
    keybottom: "fn",
    keytop: "",
    topAlign: "center",
    bottomAlign: "center",
    justify: "center",
  },
  {
    width: "normal",
    keybottom: "",
    keytop: FaWindows,
    topAlign: "center",
    bottomAlign: "center",
    justify: "center",
  },
  {
    width: "normal",
    keybottom: "alt",
    keytop: "",
    topAlign: "center",
    bottomAlign: "center",
    justify: "center",
  },
  {
    width: "3xl",
    keybottom: "",
    keytop: "",
    topAlign: "center",
    bottomAlign: "center",
    justify: "center",
  }, // spacebar
  {
    width: "normal",
    keybottom: "alt",
    keytop: "",
    topAlign: "center",
    bottomAlign: "center",
    justify: "center",
  },
  {
    width: "normal",
    keybottom: "ctrl",
    keytop: "",
    topAlign: "center",
    bottomAlign: "right",
    justify: "center",
  },
  {
    width: "normal",
    keytop: FaChevronLeft,
    topAlign: "center",
    justify: "center",
  },
];
